---
name: CI

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
          run_install: false

      - name: Show versions
        run: |
          node -v
          corepack -v || true
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Typecheck (tests)
        run: pnpm typecheck:test

      - name: Typecheck (e2e)
        run: pnpm typecheck:e2e

      - name: Unit tests (Vitest)
        run: pnpm test

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: E2E tests (Playwright)
        run: pnpm e2e

      - name: Build
        run: pnpm build
